# Generated by Django 5.2.17 on 2026-08-26 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_quiz_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGuide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='en', max_length=5)),
                ('pdf_file', models.FileField(upload_to='study_guides/')),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_guides', to='chatapp.document')),
            ],
        ),
    ]
